name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install
        working-directory: ./frontend

      - name: Build
        run: yarn build
        working-directory: ./frontend

      - name: Deploy to Vercel
        run: |
          yarn global add vercel
          vercel --prod --token=$VERCEL_TOKEN --confirm \
            --org $VERCEL_ORG_ID \
            --project $VERCEL_PROJECT_ID
        working-directory: ./frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
